[package]
name = "adhesion"
version = "0.1.0"
edition = "2021"
authors = ["amy universe <nopenullnilvoid00@gmail.com>"]
repository = "https://github.com/tomara-x/adhesion"

[dependencies]
bevy = { version = "0.12.0", features = ["dynamic_linking"] }
rand = "0.8.0"
bevy_pancam = "0.10.0"
bevy_prototype_lyon = "0.10.0"
bevy_vector_shapes = "0.6.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

